---

- name: Create protocol directory
  ansible.builtin.file:
    path: "{{ deploy_ioc_ioc_directory }}/protocol"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    state: directory
    mode: "0775"

- name: Install base startup script
  ansible.builtin.template:
    src: "base.cmd.j2"
    dest: "{{ deploy_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
