---

- name: Install udev file for QEPro
  ansible.builtin.template:
    src: "90-qepro.rules.j2"
    dest: "/etc/udev/rules.d/90-qepro.rules"
    owner: root
    group: root
    mode: "0644"
  notify: Reload udev rules


- name: Install base startup script
  ansible.builtin.template:
    src: "base.cmd.j2"
    dest: "{{ deploy_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
