---

type: enum("adxspd")
environment:
  ENGINEER: str()
  PREFIX: str()
  XSIZE: int()
  YSIZE: int()
  NUM_MODULES: int()
  IP: any(hostname(), ip())
  PORT_NUM: int()

  # Optional device identifier.
  # If not specified, first device discovered will be used.
  DEVICE_ID: str(required=False)
