---

ADPhantom:
  type: "adphantom"
  environment:
    PREFIX: "XF:31ID1-ES{VEO:Cam-1}"
    ENGINEER: "K. Barry"
    MAC_ADDR: "1423f21fdeb0"
    INTF: "eno5"
    CAMERA_IP: "100.100.214.107"
    NUM_CINES: 16
