---
type: enum("adphantom")
environment:
  ENGINEER: str()
  PREFIX: str()
  CAMERA_IP: any(ip(), hostname())
  NUM_CINES: int()
  MAC_ADDR: str()
  INTF: str()
  XSIZE: int(required=False)
  YSIZE: int(required=False)
  CTRL_PORT: int(required=False)
  DATA_PORT: int(required=False)
  PORT: str(required=False)
