---

type: enum("omega_rtc")
devices: list(device)
environment:
  ENGINEER: str()
  PREFIX: str()
  SYS: str()
device:
  SYS: str()
  DEV: str()
  PORT: str()
  HOST: str()
  COMM: enum("RS-232", "RS-485")
