---

motorpigcs2-01:
  type: motorpigcs2
  environment:
    ENGINEER: "J. MA"
    PORT: "GCS2"
    ASYN_PORT: "GCS2_ETH"
    P: "XF:31ID-ES"
    R: "{GCS2:1}"
    PREFIX: "$(P)$(R)"
    CT_PREFIX: "XF:31ID-CT{GCS2:1}"
    CONTROLLER_IP: "10.66.xx.xx"
    CONTROLLER_PORT: 50000
  axes:
    - suffix: "{Gon:1-Ax:XP}Mtr"
      addr: 0
      desc: "Fine Motion X"
      egu: "um"
      dir: "Pos"
      velo: 5
      vbas: 0
      accl: 0.2
      bdst: 0
      bvel: 1
      bacc: 0.2
      mres: 0.0001
      prec: 4
      dhlm: 0
      dllm: 0
      init: ""
    - suffix: "{Gon:1-Ax:YP}Mtr"
      addr: 1
      desc: "Fine Motion Y"
      egu: "um"
      dir: "Pos"
      velo: 5
      vbas: 0
      accl: 0.2
      bdst: 0
      bvel: 1
      bacc: 0.2
      mres: 0.0001
      prec: 4
      dhlm: 0
      dllm: 0
      init: ""
    - suffix: "{Gon:1-Ax:ZP}Mtr"
      addr: 2
      desc: "Fine Motion Z"
      egu: "um"
      dir: "Pos"
      velo: 5
      vbas: 0
      accl: 0.2
      bdst: 0
      bvel: 1
      bacc: 0.2
      mres: 0.0001
      prec: 4
      dhlm: 0
      dllm: 0
      init: ""
