---
adphantom_afefafc:
  name: ADPhantom
  executable: phantomApp
  version: afefafc
  url: https://github.com/jwlodek/ADPhantom
  include_base_ad_config: true
  module_deps:
    - adcore_60080dc
  pkg_deps:
    - libpcap-devel
