---

mrftiming_3bb9fcf:
  name: MRFTiming
  version: 3bb9fcf
  url: https://github.com/NSLS2/MRFTiming
  module_deps:
    - epics-mrf
    - elauncher
  epics_deps:
    MRF: /epics/modules/epics-mrf
    ELAUNCHER: /epics/modules/elauncher
