---
nsls2em_20fb70b:
  name: nsls2em
  version: 20fb70b
  url: https://github.com/NSLS2/nsls2em-ioc
  include_base_ad_config: true
  executable: nsls2em
  module_deps:
    - std_1b416db
    - pscdrv_1ed650d
    - quadem_f5ab1e9
