---
nsls2em_dac28e9:
  name: nsls2em
  version: dac28e9
  url: https://github.com/NSLS2/nsls2em-ioc
  include_base_ad_config: true
  executable: nsls2em
  module_deps:
    - std_1b416db
    - pscdrv_1ed650d
    - quadem_f5ab1e9
