---

snmp_nscl_3cd2804:
  name: SNMP-NSCL
  version: 3cd2804
  url: https://github.com/NSLS2/snmp-nscl
  include_base_ad_config: false
  executable: snmp
  module_deps: []
  pkg_deps:
    - net-snmp
    - net-snmp-devel
