---

deploy_ioc_use_common: true
deploy_ioc_use_ad_common: true
deploy_ioc_required_module: adpco_b17fe13
deploy_ioc_as_dir_name: autosave
deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/pcoIOC"

deploy_ioc_req_file_list:
  - name: auto_settings.req
    macros: "P=$(PREFIX)"


deploy_ioc_os_env_exports:
  LD_LIBRARY_PATH: "/opt/pco/pco.sdk/lib:/opt/pco/pco.cpp/lib"

deploy_ioc_device_specific_env:
  CBUFFS: 500
  MAX_THREADS: 8
  NCHANS: 2048
  PORT: PCO1
  QSIZE: 20
  NELEMENTS: 5000000
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db"
