---
deploy_ioc_use_common: false
deploy_ioc_use_ad_common: true
deploy_ioc_required_module: adtucam_0c04e68
deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/tucamIOC"
deploy_ioc_device_specific_env:
  PORT: "AXIS1"
  QSIZE: 20
  XSIZE: 4096
  YSIZE: 4096
  NCHANS: 2048
  CBUFFS: 500
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db:$(ADTUCAM)/db"
