---

deploy_ioc_use_ad_common: true
deploy_ioc_required_module: adxspd_latest
deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/xspdIOC"
deploy_ioc_req_file_list:
  - name: auto_settings.req
    macros: "P=$(PREFIX)"
deploy_ioc_device_specific_env:
  PORT: "XSPD1"
  QSIZE: 20
  NCHANS: 2048
  CBUFFS: 500
  MAX_THREADS: 8
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db"
