---

deploy_ioc_use_common: false
deploy_ioc_use_ad_common: false
deploy_ioc_required_module: base_stream_ioc_093e6cf
deploy_ioc_device_specific_env: {}
deploy_ioc_template_root_path: "{{ deploy_ioc_required_module_path }}"
