---

deploy_ioc_use_common: true
deploy_ioc_use_ad_common: false
deploy_ioc_required_module: omega_rtc_db3cc53
deploy_ioc_executable: omegaCNi32
deploy_ioc_make_autosave_files: true
deploy_ioc_template_root_path: "{{ deploy_ioc_required_module_path }}"
