---
deploy_ioc_required_module: snmp_nscl_3cd2804
deploy_ioc_template_root_path: "{{ deploy_ioc_required_module_path }}"
deploy_ioc_make_autosave_files: true
deploy_ioc_req_file_list:
  - name: "info_settings.req"
    macros: ""
  - name: "info_positions.req"
    macros: ""
