[workspace]
authors = ["Jakub Wlodek <jwlodek@bnl.gov>"]
channels = ["conda-forge"]
name = "IOC Deployment Verifier"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.verification]
args = [
    "ioc_name"
]
cmd = "./verify_deployment.py verify.yml /epics/iocs/{{ ioc_name }}"

[dependencies]
python = "3.13.*"
pyyaml = ">=6.0.3,<7"
