---

f460-01:
  type: f460
  ioc_template_root_path: /epics/modules/F460
  environment:
    ENGINEER: K. Barry
    SYS: XF:31ID-ES
    DEV: "{F460:1}"
    IOC_SYS: XF:31ID-CT
    IOC_DEV: "{IOC:F460}"  # Used for IOC-specific PVs
    PORT: E1
    HOST: xf31id1-lab3-tsrv1.nsls2.bnl.local:4008
