---

pi-e621:
  type: "pi-e621"

  environment:
    HOST: "xf09id1-tsrv6.nsls2.bnl.gov:4001"
    PI_PORT: "PI_VMS"
    SYS: "XF:09IDA-OP:1"
    IOC_SYS: "XF:09IDA-CT"
    IOC_DEV: "IOC:PZT3"
    ASYN_DEV: "MC:PZT3"
    IOC_PREFIX: $(IOC_SYS){$(IOC_DEV)}
    ASYN_PREFIX: $(IOC_SYS){$(ASYN_DEV)}
    ENGINEER: "C. Engineer"
    EGU: "urad"
    TWV: "1"
    VELO: "5."
    VBAS: "2.0"
    ACCL: "0.1"
    BDST: "0"
    BVEL: "1"
    BACC: ".2"
    MRES: "0.000001"
    PREC: "3"
    DHLM: "0"
    DLLM: "0"
    INIT: ""
