---

pi-e621:
  type: "pi-e621"

  environment:
    HOST: "xf09id1-tsrv6.nsls2.bnl.gov:4001"
    PI_PORT: "PI_VMS"
    SYS: "XF:09IDA-OP:1"
    IOC_SYS: "XF:09IDA-CT"
    IOC_DEV: "IOC:PZT3"
    ASYN_DEV: "MC:PZT3"
    IOC_PREFIX: $(IOC_SYS){$(IOC_DEV)}
    ASYN_PREFIX: $(IOC_SYS){$(ASYN_DEV)}
    ENGINEER: "C. Engineer"

  substitutions:
    motors:
      - filepath: "$(PIE621)/db/asyn_motor.db"
        template_macros: "_P=$(SYS),_PI_PORT=$(PI_PORT)"
        pattern:
          [
            "P",
            "PORT",
            "ADDR",
            "DTYP",
            "ALIAS",
            "DESC",
            "EGU",
            "DIR",
            "TWV",
            "VELO",
            "VBAS",
            "ACCL",
            "BDST",
            "BVEL",
            "BACC",
            "MRES",
            "PREC",
            "DHLM",
            "DLLM",
            "INIT",
          ]
        instances:
          - [
            "$(_P){Mono:HDCM-Ax:FP}",
            "$(_PI_PORT)",
            "0",
            "asynMotor",
            "vms_pf",
            "vms_pf",
            "urad",
            "Pos",
            "1",
            "5.",
            "2.0",
            "0.1",
            "0",
            "1",
            ".2",
            "0.000001",
            "3",
            "0",
            "0",
            ""
          ]
