---

type: enum("pi-e621")
environment:
  ENGINEER: str()
  HOST: str()
  PI_PORT: str()
  SYS: str()
  IOC_SYS: str()
  IOC_DEV: str()
  ASYN_DEV: str()
  IOC_PREFIX: str()
  ASYN_PREFIX: str()
  EGU: str(required=False)
  TWV: str(required=False)
  VELO: str(required=False)
  VBAS: str(required=False)
  ACCL: str(required=False)
  BDST: str(required=False)
  BVEL: str(required=False)
  BACC: str(required=False)
  MRES: str(required=False)
  PREC: str(required=False)
  DHLM: str(required=False)
  DLLM: str(required=False)
  INIT: str(required=False)
