---

type: enum("pi_e621")
environment:
  ENGINEER: str()
  HOST: any(ip(), hostname())
  HOST_PORT: int(min=1, max=65535)
  PI_PORT: str()
  SYS: str()
  IOC_SYS: str()
  IOC_DEV: str()
  ASYN_DEV: str()
  IOC_PREFIX: str()
  ASYN_PREFIX: str()
  EGU: str(required=False)
  TWV: str(required=False)
  VELO: str(required=False)
  VBAS: str(required=False)
  ACCL: str(required=False)
  BDST: str(required=False)
  BVEL: str(required=False)
  BACC: str(required=False)
  MRES: str(required=False)
  PREC: str(required=False)
  DHLM: str(required=False)
  DLLM: str(required=False)
  INIT: str(required=False)
motors: list(include('motor'), min=1)

---
motor:
  prefix: str()
  suffix: str()
  addr: int()
  alias: str()
  desc: str()
  egu: str()
  twv: str()
  velo: str()
  vbas: str()
  accl: str()
  bdst: str()
  bvel: str()
  bacc: str()
  mres: str()
  prec: str()
  dhlm: str()
  dllm: str()
  init: str()
