---

type: enum("motorpigcs2")

environment:
  ENGINEER: str()
  PORT: str()
  ASYN_PORT: str()
  P: str()
  R: str()
  PREFIX: str()
  CT_PREFIX: str()
  CONTROLLER_IP: any(ip(), hostname())
  CONTROLLER_PORT: int(min=1, max=65535, default=50000)

axes: list(include('axis'))

---

axis:
  suffix: str()
  addr: int()
  desc: str()
  egu: str()
  dir: str()
  velo: num()
  vbas: num()
  accl: num()
  bdst: num()
  bvel: num()
  bacc: num()
  mres: num()
  prec: int()
  dhlm: num()
  dllm: num()
  init: str()
